// Generated by Framer (cec372b)
import { jsx as _jsx } from "react/jsx-runtime"
import { addFonts, addPropertyControls, ControlType, cx, RichText, useVariantState, withCSS } from "framer"
import { LayoutGroup, motion } from "framer-motion"
import * as React from "react"
const cycleOrder = ["qn_wVNcPD"]
const variantClassNames = { qn_wVNcPD: "framer-v-1ygbj9a" }
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]))
  return nextOverrides
}
const humanReadableVariantMap = {}
const transitions = {
  default: { damping: 60, delay: 0, duration: 0.3, ease: [0.44, 0, 0.56, 1], mass: 1, stiffness: 500, type: "spring" },
}
const BASE62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
function useRandomID() {
  const ref = React.useRef(null)
  if (ref.current === null) {
    ref.current = Array(5)
      .fill(0)
      .map(() => BASE62[Math.floor(Math.random() * BASE62.length)])
      .join("")
  }
  return ref.current
}
const Component = /*#__PURE__*/ React.forwardRef(function (
  {
    id,
    style: externalStyle = {},
    className,
    width,
    height,
    layoutId,
    variant: outerVariant = "qn_wVNcPD",
    title: haXn00h0k = "Hey",
    ...restProps
  },
  ref
) {
  const outerVariantId = humanReadableVariantMap[outerVariant]
  const variant = outerVariantId || outerVariant
  const { baseVariant, classNames, gestureVariant, setGestureState, setVariant, transition, variants } =
    useVariantState({ cycleOrder, defaultVariant: "qn_wVNcPD", transitions, variant, variantClassNames })
  const layoutDependency = variants.join("-") + restProps.layoutDependency
  const defaultLayoutId = useRandomID()
  const { pointerEvents, ...style } = externalStyle
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(motion.div, {
      "data-framer-generated": true,
      initial: variant,
      animate: variants,
      onHoverStart: () => setGestureState({ isHovered: true }),
      onHoverEnd: () => setGestureState({ isHovered: false }),
      onTapStart: () => setGestureState({ isPressed: true }),
      onTap: () => setGestureState({ isPressed: false }),
      onTapCancel: () => setGestureState({ isPressed: false }),
      className: cx("framer-vkO53", classNames),
      style: {
        display: "contents",
        pointerEvents: pointerEvents !== null && pointerEvents !== void 0 ? pointerEvents : undefined,
      },
      children: /*#__PURE__*/ _jsx(motion.div, {
        ...restProps,
        className: cx("framer-1ygbj9a", className),
        "data-framer-name": "Variant 1",
        layoutDependency: layoutDependency,
        layoutId: "qn_wVNcPD",
        ref: ref,
        style: { backgroundColor: "rgb(183, 53, 222)", ...style },
        transition: transition,
        children: /*#__PURE__*/ _jsx(RichText, {
          __fromCanvasComponent: true,
          children: /*#__PURE__*/ _jsx(React.Fragment, { children: /*#__PURE__*/ _jsx(motion.p, { children: "Hey" }) }),
          className: "framer-1u3f47s",
          layoutDependency: layoutDependency,
          layoutId: "DLzpoWDf4",
          style: {
            "--framer-link-text-color": "rgb(0, 153, 255)",
            "--framer-link-text-decoration": "underline",
            "--framer-paragraph-spacing": "0px",
          },
          text: haXn00h0k,
          transition: transition,
          verticalAlignment: "top",
          withExternalLayout: true,
        }),
      }),
    }),
  })
})
const css = [
  '.framer-vkO53 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-vkO53 * { box-sizing: border-box; }",
  ".framer-vkO53 .framer-5vkim3 { display: block; }",
  ".framer-vkO53 .framer-1ygbj9a { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 10px 20px 10px 20px; position: relative; width: min-content; }",
  ".framer-vkO53 .framer-1u3f47s { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vkO53 .framer-1ygbj9a { gap: 0px; } .framer-vkO53 .framer-1ygbj9a > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-vkO53 .framer-1ygbj9a > :first-child { margin-left: 0px; } .framer-vkO53 .framer-1ygbj9a > :last-child { margin-right: 0px; } }",
]
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 39
 * @framerIntrinsicWidth 70
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"haXn00h0k":"title"}
 */ const FramerfYrOFb2zP = withCSS(Component, css)
export default FramerfYrOFb2zP
FramerfYrOFb2zP.displayName = "Button"
FramerfYrOFb2zP.defaultProps = { height: 39, width: 70 }
addPropertyControls(FramerfYrOFb2zP, {
  haXn00h0k: { defaultValue: "Hey", displayTextArea: false, title: "Title", type: ControlType.String },
})
addFonts(FramerfYrOFb2zP, [])
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerfYrOFb2zP",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerVariables: '{"haXn00h0k":"title"}',
        framerIntrinsicHeight: "39",
        framerIntrinsicWidth: "70",
        framerCanvasComponentVariantDetails: '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
}
//# sourceMappingURL=./fYrOFb2zP.map
